version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myflaskapp
    ports:
      - "3307:3306"
    networks:
      - app_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  microproducts:
    build: ./microProducts
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - app_network

  microusers:
    build: ./microUsers
    ports:
      - "5002:5002"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

